### ISSUE TITLE
Clipboard paste fails on macOS

### ISSUE THREAD

**Issue by Rekkonnect** [Rekkonnect/Syndiesis#27]
Clipboard paste fails when there is no code editor tag assigned to the clipboard data object. This happens on macOS, and perhaps other platforms.

Credits to @elvodqa for discovering this

**Comment by elvodqa** [comment]
LGTM!!

**Comment by Rekkonnect** [comment]
Closed via 9908f1b08a1d92afc9cc26d60e0d9d6586425842
